export enum ValidationError {
    Required = 'shared.validation.required',
    MinLength = 'shared.validation.min-length-n',
    MaxLength = 'shared.validation.max-length-n',
    MinValue = 'shared.validation.min-value-n',
    MaxValue = 'shared.validation.max-value-n',
    MinValueIncluding = 'shared.validation.min-value-including-n',
    MaxValueIncluding = 'shared.validation.max-value-including-n',
    ArrayNotEmpty = 'shared.validation.array-not-empty',
    ArrayMinItems = 'shared.validation.array-min-items-n',
    ArrayMaxItems = 'shared.validation.array-max-items-n',
    MinDate = 'shared.validation.date-after-n',
    MaxDate = 'shared.validation.date-before-n',
    Duplicate = 'shared.validation.duplicate',
    InvalidValue = 'shared.validation.invalid-value',
    InvalidNumber = 'shared.validation.invalid-number',
    InvalidDate = 'shared.validation.invalid-date',
    InvalidEmail = 'shared.validation.invalid-email',
}
